# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: iLISTEN 2018

# Short description (goes below the title; it will also be used in the RSS feed)
description: iLISTEN, the first itaLIan Speech acT labEliNg task at Evalita 2018

# Your name, as you want it to appear underneath each post and in the footer
author: iLISTEN 2018 organizers

# Your email if you want it to be linked on the contact page
author_email: ilisten.evalita2018@gmail.com

theme: jekyll-theme-slate
